### ISSUE TITLE
add unmanaged code area for imports

### ISSUE THREAD

**Issue by domdorn** [zalando/api-first-hand#43]
when filling the methods in the generated actions, it often happens that another type has to be imported. 

Allow to put this import into an unmanaged area, so it does not get removed on file-regeneration

**Comment by s12v** [comment]
👍 would be really useful, looking forward

**Comment by LappleApple** [comment]
Hi @domdorn and @s12v, if you would like to work on this/contribute a PR, that would be great.

**Comment by LappleApple** [comment]
Haha @s12v, just realized who you are. :) Need to get used to your username :)

**Comment by s12v** [comment]
@domdorn, should be solved in 0.2.0: https://github.com/zalando/api-first-hand/blob/master/play-scala-generator/src/main/resources/play_scala_controller.mustache#L16-L22

**Comment by domdorn** [comment]
awesome! is 0.2.0 already released? didn't see it in the tags

**Comment by slavaschmidt** [comment]
negative, we still have some serious issues wie are working on, sorry
